<!-- Footer with additional site information and contact, standard on all pages. -->
<footer>
	<nav>
		<a href="https://github.com/JunoPittardSwin/Applied-Web-Project-P2" target="_blank">GitHub Repository</a>
		<a href="https://junopittardswin.atlassian.net/jira/software/projects/SCRUM/summary" target="_blank">Jira Project</a>
		<a href="mailto:info@watertightrecruitment.com">Contact Us</a>
		<a href="./login.php">Login</a>
	</nav>

	<div class="copyright-notice">
		&copy; 2025 Watertight Recruitment. All rights reserved.
		<br>
		Background photos are &copy; Various Authors, Pexels (<a href="https://www.pexels.com/license/">License</a>)
	</div>
</footer>
